project:
  type: website
  output-dir: docs

website:
  title: "PORTFOLIO"
  # This ensures the navbar stays sticky at the top while scrolling
  navbar:
    background: primary
    search: true
    left:
      - text: "Projects"
        file: Projects.qmd
      - text: "About"
        file: about.qmd
      - text: "Contact"
        file: contact.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly # Give your users a dark mode option!
    css: styles.css
    toc: false
    back-to-top-navigation: true
    # This helps with that "empty right space" issue
    page-layout: article

editor: visual